### ISSUE TITLE
When I run the program, I've been stuck in this position

### ISSUE THREAD

**Issue by yongkaili** [ankitdhall/lidar_camera_calibration#26]
Thank you for all the work you have done！！
When I run the program, I've been stuck in this position

exbot@robot:~/seg_ws$ roslaunch lidar_camera_calibration find_transform.launch 
... logging to /home/exbot/.ros/log/1389abea-d635-11e7-978d-b8975ac33022/roslaunch-robot-19991.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://robot:39300/

SUMMARY
========

PARAMETERS
 * /aruco_mapping/calibration_file: /home/exbot/seg_w...
 * /aruco_mapping/marker_size: 0.207
 * /aruco_mapping/num_of_markers: 2
 * /aruco_mapping/roi_allowed: False
 * /aruco_mapping/space_type: plane
 * /lidar_camera_calibration/camera_frame_topic: /camera/rgb/image...
 * /lidar_camera_calibration/camera_info_topic: /camera/rgb/camer...
 * /lidar_camera_calibration/velodyne_topic: /velodyne_points
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    aruco_mapping (aruco_mapping/aruco_mapping)
    find_transform (lidar_camera_calibration/find_transform)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[aruco_mapping-1]: started with pid [20009]
process[find_transform-2]: started with pid [20010]
[ INFO] [1512098234.389068869]: Calibration file path: /home/exbot/seg_ws/src/aruco_mapping/data/zed_left_uurmi.ini
[ INFO] [1512098234.389137636]: Number of markers: 2
[ INFO] [1512098234.389169334]: Marker Size: 0.207
[ INFO] [1512098234.389186190]: Type of space: plane
[ INFO] [1512098234.389215743]: ROI allowed: 0
[ INFO] [1512098234.389235967]: ROI x-coor: 0
[ INFO] [1512098234.389251696]: ROI y-coor: 0
[ INFO] [1512098234.389265392]: ROI width: 32576
[ INFO] [1512098234.389278377]: ROI height: 4273583
[ INFO] [1512098234.390848820]: Calibration data loaded successfully
Size of the frame: 640 x 480
Limits: -1.5 to 1.5
Limits: -1.5 to 1.5
Limits: 0 to 3
Number of markers: 2
Intensity threshold (between 0.0 and 1.0): 0.01
useCameraInfo: 0
Projection matrix: 
[541.53827, 0, 309.19846, 0;
  0, 541.88391, 234.94804, 0;
  0, 0, 1, 0]
MAX_ITERS: 100
[ INFO] [1512098234.446563774]: Reading CameraInfo from configuration file
100=(240.526,224.147) (280.594,264.826) (240.282,304.936) (201.141,263.979) Txyz=-0.248869 0.106907 1.96283 Rxyz=-0.619671 -1.69843 1.76172 
180=(376.31,345.552) (337.306,305.144) (377.607,265.207) (416.413,306.024) Txyz=0.247798 0.257583 1.98183 Rxyz=-1.46249 0.537823 -0.655972 
[ INFO] [1512098238.688796955]: First marker with ID: 100 detected
[ WARN] [1512098238.691812183]: TF to MSG: Quaternion Not Properly Normalized
100=(240.47,224.216) (280.5,264.74) (240.568,304.809) (201.005,264.215) Txyz=-0.24944 0.107319 1.96808 Rxyz=-0.636058 -1.71376 1.75153 
180=(376.51,345.975) (337.219,305.229) (377.612,265.202) (416.801,306.303) Txyz=0.247346 0.257336 1.9751 Rxyz=-1.48229 0.544808 -0.652409 
100=(240.562,224.118) (280.593,264.826) (240.25,304.968) (200.947,264.038) Txyz=-0.248917 0.106914 1.96229 Rxyz=-0.631458 -1.703 1.76491 
180=(376.744,346.239) (337.357,305.162) (377.665,265.115) (416.894,306.355) Txyz=0.247381 0.256815 1.97104 Rxyz=-1.50036 0.526474 -0.67013 
100=(240.655,224.12) (280.512,264.907) (240.344,304.874) (201.089,264.175) Txyz=-0.249104 0.107202 1.96539 Rxyz=-0.627884 -1.70095 1.76401 
180=(376.921,346.28) (337.231,305.378) (377.628,265.109) (417.063,306.319) Txyz=0.247126 0.256677 1.96811 Rxyz=-1.49488 0.53991 -0.662613 
100=(240.656,224.044) (280.517,264.902) (240.285,304.933) (201.053,263.942) Txyz=-0.248732 0.106777 1.96154 Rxyz=-0.618724 -1.70001 1.76226 
180=(376.567,345.822) (337.283,305.167) (377.644,265.17) (416.95,306.326) Txyz=0.247888 0.257515 1.9779 Rxyz=-1.48503 0.558162 -0.640999 
100=(240.553,224.223) (280.53,264.854) (240.194,305.09) (200.858,264.014) Txyz=-0.249112 0.107109 1.96236 Rxyz=-0.634358 -1.70198 1.7685 

It looks like there's no new thing.why?

**Comment by blutjens** [comment]
@yongkaili 
1. You are missing these lines:
`[ INFO] [1505776483.491411935]: Velodyne scan received at 1.50578e+09`
`[ INFO] [1505776483.491425936]: marker_6dof received at 1.50578e+09`
-> make sure you are publishing lidar and camera data and then subscribing them at the same topic 
2. If that doesn't help, refer to #17
