### ISSUE TITLE
velodyne_msgs error

### ISSUE THREAD

**Issue by shivam-chandhok** [ankitdhall/lidar_camera_calibration#31]
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "velodyne_msgs"
  with any of the following names:

    velodyne_msgsConfig.cmake
    velodyne_msgs-config.cmake

  Add the installation prefix of "velodyne_msgs" to CMAKE_PREFIX_PATH or set
  "velodyne_msgs_DIR" to a directory containing one of the above files.  If
  "velodyne_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  lidar_camera_calibration/CMakeLists.txt:12 (find_package)

-- Could not find the required component 'velodyne_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "velodyne_msgs"
  with any of the following names:

    velodyne_msgsConfig.cmake
    velodyne_msgs-config.cmake

  Add the installation prefix of "velodyne_msgs" to CMAKE_PREFIX_PATH or set
  "velodyne_msgs_DIR" to a directory containing one of the above files.  If
  "velodyne_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  lidar_camera_calibration/CMakeLists.txt:12 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/shivam/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/shivam/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:290: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

**Comment by karnikram** [comment]
This is a dependency issue, it's not able to find the velodyne package. 
`sudo apt install ros-kinetic-velodyne` should solve it.

**Comment by shivam-chandhok** [comment]
It worked.Thankx a lot
