### ISSUE TITLE
How could I do 2D-3D correspondence calibration?

### ISSUE THREAD

**Issue by xiaoshuliu** [ankitdhall/lidar_camera_calibration#34]
Hi, I have read your paper, and I wonder could I just do the 2D-3D correspondence calibration without ArUco markers? Is the code for 2D-3D in this repo? Thanks.

**Comment by karnikram** [comment]
The code has not been included in this repo.

And I don't think the 2D-3D approach worked as well as this one.

**Comment by OmarBarakat1995** [comment]
@karnikram I've read the paper but couldn't get how 3D features are obtained in case of monocular . Is it because the boards are planar, thus all edge points are having same depth?

**Comment by karnikram** [comment]
Aruco gives us the 3d pose of the marker relative to the camera directly. And the coordinates of the board's corner points relative to the aruco marker are known since the board's dimensions are known. So a simple matrix multiplication can be done to obtain the coordinates of the corner points in the camera's frame.

**Comment by OmarBarakat1995** [comment]
@karnikram  Thank you .. But I am considered with the depth (3rd dimension) in case of monocular camera not stereo. let me thank you again and if I am misunderstanding something please refer me to a read .

**Comment by xiaoshuliu** [comment]
@karnikram How does ArUco give us the 3d pose? Is it the same principle as the chess board, but just use a different library?

**Comment by karnikram** [comment]
@OmarBarakat1995  Stereo images are not being used for pose estimation here, only monocular. Aruco markers or any fiducial markers can be used for monocular pose estimation. Refer to [this](http://www.uco.es/investiga/grupos/ava/sites/default/files/GarridoJurado2014.pdf) for an explanation of the arcuo library.

**Comment by OmarBarakat1995** [comment]
@karnikram we have configured the files to calibrate our monocamera with vlp lidar... On launching the find_transform launch file we get this error. 
![image](https://user-images.githubusercontent.com/24323903/35803637-2b874000-0a7d-11e8-89b2-109cbce7a8cd.png)
please note that we used the camera calibrator which provided us with .yaml camera parameters file and amother .text file , we couldn't find an explicit .ini file so we renamed the text file tochange its extension and provided its path to the launch file parameter default value.
