### ISSUE TITLE
find_transform.launch doesn't respond after detecting first marker (if the second is in the scene)

### ISSUE THREAD

**Issue by OmarBarakat1995** [ankitdhall/lidar_camera_calibration#35]
![image](https://user-images.githubusercontent.com/24323903/35856154-c49c495a-0b3d-11e8-8e2c-11c16bbe9e76.png)

**Comment by blutjens** [comment]
@OmarBarakat1995 Check that your calibration path in find_transforms.launch points to your camera's intrinsic parameter file (e.g. 'zed_left_uurmi.ini'). You can receive the values for your intrinsic camera by calling $ rostopic echo /your_camera/camera_info.

**Comment by villanuevab** [comment]
I am getting the same issue (except no warning for incorrect calibration). I encountered the issue when trying to use a non-velodyne lidar.

**Comment by villanuevab** [comment]
I am encountering the same issue. Is the correct calibration file needed to run? I recognize it's needed for a good result, but I didn't think it would interrupt the calibration process.
