### ISSUE TITLE
Links to video are broken

### ISSUE THREAD

**Issue by va9abund** [ankitdhall/lidar_camera_calibration#38]
Hello.

Please update links to Youtube you provided.

Best regards, Alex.

**Comment by ankitdhall** [comment]
@va9abund the video links seem to be fine. Could you try them again or let me know which one seems broken to you?

**Comment by va9abund** [comment]
The first one in usage section (https://youtu.be/SiPGPwNKE-Q), in "Fusion using..."(https://youtu.be/AbjRDtHLdz0) and "Calibrating cameras ... " (https://youtu.be/Om1SFPAZ5Lc).

**Comment by ankitdhall** [comment]
They seem to work fine for me. :disappointed:

**Comment by va9abund** [comment]
Could you write me the name of the youtube chanel and close the issue? Thanks :)

**Comment by ankitdhall** [comment]
Here is the link to the playlist [link](https://www.youtube.com/playlist?list=PLoeQ9AU3xgsrsj9iS2sMMUnHZTLuCejeA).
