### ISSUE TITLE
Difference between "Average RMSE" and "RMSE on average transformation"?

### ISSUE THREAD

**Issue by villanuevab** [ankitdhall/lidar_camera_calibration#49]
What is the difference between the two reported RMSE values? And which one is plotted in https://github.com/ankitdhall/lidar_camera_calibration/issues/22 ?
```
Average RMSE is: 0.02554
RMSE on average transformation is: 0.078944
```
Thanks for your time!

**Comment by karnikram** [comment]
Average RMSE is the average of the RMSEs from all the iterations. The RMSE at each iteration is calculated using that iteration's estimate of the transformation, and they're all added up together to calculate the "Average RMSE".

The second value is the RMSE calculated using the average transformation, and this is what is shown on the plot as well.

Hope this helps!
