### ISSUE TITLE
catkin_make issues

### ISSUE THREAD

**Issue by aashi7** [ankitdhall/lidar_camera_calibration#50]
Hi,

For ROS-Kinetic, it seems that most tutorials mention a very simple procedure by copying to /catkin_ws/src and running catkin_make

as shown here
https://github.com/eYSIP-2017/eYSIP-2017_Navigation-in-Indoor-Environments-using-drone/wiki/Setup-ArUco-Mapping-package
and
https://github.com/warp1337/ros_aruco

Unfortunately, after long hours of trying, this still leads to "aruco_msgs" missing configuration file, or 'aruco'

Following
#49
and installing aruco, aruco-ros, aruco-msgs, and aruco-mapping from apt, i.e. sudo apt install ros-kinetic-aruco

but once these are installed from apt, compiling another library leads to issues.
We are trying to compile
https://github.com/ankitdhall/lidar_camera_calibration
and it leads to 'lidar_camera_calibration" missing configuration file when running catkin_make
yet it works fine without that folder in the src folder.

Anyone have a similar experience?

We tried building non-aruco libraries from src with catkin_make, and it was successful. Our feeling is that something goes wrong with aruco builds, hence it can't even make them from source but can only do so after installing from apt.

Thanks,

**Comment by karnikram** [comment]
The version of aruco_mapping that is included in this package is slightly modified. Installing the latest binary directly will not make it work.
Running the following commands should solve your problem, I think
```
catkin_make -DCATKIN_WHITELIST_PACKAGES="aruco;aruco_ros;aruco_msgs"
catkin_make -DCATKIN_WHITELIST_PACKAGES="aruco_mapping;lidar_camera_calibration"
catkin_make -DCATKIN_WHITELIST_PACKAGES=""

```
