### ISSUE TITLE
how to make 100 iterations?

### ISSUE THREAD

**Issue by OYZJ** [ankitdhall/lidar_camera_calibration#52]
Hi ankitdhall, May I ask how can I modify your code to run 100 iterations? I met very poor result with only one iteration. And according to your paper it seem the accuracy can be improved a lot by increase the iteration numbers.
Thanks in advance.

**Comment by blutjens** [comment]
Change the penultimate line in conf/config_file.txt from "1" to "100". The default parameter is 100, however. Your issue might be caused by something else.

**Comment by OYZJ** [comment]
Hello blutjens, Thanks for your help. But the problem is I can't see how this program can reach 100 iteration. I have read through the all the code in src and include. And from the Find_RT.h it seems the iter will never reach to the max_iters without modification.

**Comment by karnikram** [comment]
The code does by default run for 100 iterations. The check is done [here](https://github.com/ankitdhall/lidar_camera_calibration/blob/edbcf7823f74515f621aa01d67cfc963b7f32d14/src/Corners.cpp#L255).

Something else is going wrong for you.

**Comment by lihaolai** [comment]
hi, I met the same issue.The parameter in the conf/config_file.txt is 100.
![screenshot from 2018-06-26 11-31-54](https://user-images.githubusercontent.com/33352875/41887808-eac00aa8-7934-11e8-8a01-a478df6e8930.png)
but still only one iteration.
![screenshot from 2018-06-26 11-31-32](https://user-images.githubusercontent.com/33352875/41887841-10de0a78-7935-11e8-991c-d7c19dc0ac94.png)
how can i get it worked on 100 iterations?

**Comment by sssoubl** [comment]
repeat "rosbag play --clock ***.bag"!
