### ISSUE TITLE
how to examine the result with a monocular camera a velodyne16?

### ISSUE THREAD

**Issue by ahandsomeperson** [ankitdhall/lidar_camera_calibration#57]
Hi ankitdhall, i have got a result from lidar_camera_calibration with a velodyne16 and a monocular camera. But i don't have a zed camera. So how can i examine the result with the monocular camera and velodyne16?

**Comment by karnikram** [comment]
#19 could help.

**Comment by lihaolai** [comment]
than you

**Comment by lihaolai** [comment]
Thank you!

**Comment by GeeKmyself** [comment]
@lihaolai , hi , could u tell me how to  calibrate lidar and mono camera by this method , i am confused with how to find "3D Point correspondences in the Camera Frame" in paper.

**Comment by lihaolai** [comment]
@Chrislzy1993 i used depth pointclout from rgbd camera to correspond to the 3d velodyne16 pointcloud. but it is not very good in result. maybe we can add qq or wechat to discuss this together
