### ISSUE TITLE
preciseness of final rotation depends on accurate initial rotation?

### ISSUE THREAD

**Issue by oaix** [ankitdhall/lidar_camera_calibration#67]
@karnikram @jediofgever @villanuevab
Thank you for your reply timely and patiently.
In consideration of `Eigen::Matrix3d final_rotation = rotation_avg * lidarToCamera`[#30](https://github.com/ankitdhall/lidar_camera_calibration/issues/30) and `lidarToCamera` is the initial configurable rotation between the lidar and the camera. The accuracy of initial `rot_x`, `rot_y`, and `rot_z` will impact the preciseness of final rotation. How can I get an accurate initial rotation to guarantee the preciseness of final rotation?
Here is my calibration result. Transform point cloud of lidar to camera coordinate. The color of point represents the depth of point in lidar coordinate. Could you please give me some advise to improve calibration preciseness? Thank you very much!
![1](https://user-images.githubusercontent.com/10334694/47829351-0578d900-ddc2-11e8-9d3c-b58b90fb2b19.jpeg)

**Comment by oaix** [comment]
I got the problem. Thanks all the same!

**Comment by SiddhantNadkarni** [comment]
How did you resolve this?

**Comment by SiddhantNadkarni** [comment]
I have the same issue..

**Comment by jamesheatonrdm** [comment]
> I got the problem. Thanks all the same!

Please tell us how you fixed the problem.
