### ISSUE TITLE
Cannot detect Velodyne, Process stops

### ISSUE THREAD

**Issue by Jitesh17** [ankitdhall/lidar_camera_calibration#68]
Hi,

I'm using simple webcam and Velodine-16 for calibration. 

Process **stops** here, after the line *First marker with ID: 26 detected*, as shown below.
![termi4](https://user-images.githubusercontent.com/10935498/48169291-0cf63000-e336-11e8-9df7-a586b825283c.png)

![rosgraph5](https://user-images.githubusercontent.com/10935498/47972863-b09bd200-e0e3-11e8-8a3b-fdb79836a314.png)

[config_file.txt](https://github.com/ankitdhall/lidar_camera_calibration/files/2546538/config_file.txt)
[marker_coordinates.txt](https://github.com/ankitdhall/lidar_camera_calibration/files/2546539/marker_coordinates.txt)
```
﻿lidar_camera_calibration:
  camera_frame_topic: /image_raw
  camera_info_topic: /image_raw
  velodyne_topic: /ns1/velodyne_points
```
[zed_left_uurmi.ini.txt](https://github.com/ankitdhall/lidar_camera_calibration/files/2546551/zed_left_uurmi.ini.txt)
[aruco_config.rviz.txt](https://github.com/ankitdhall/lidar_camera_calibration/files/2546547/aruco_config.rviz.txt)
[aruco_mapping.launch.txt](https://github.com/ankitdhall/lidar_camera_calibration/files/2546548/aruco_mapping.launch.txt)

These are all the files I may have made some changes. I don't understand what changes will make it work.

**Comment by Jitesh17** [comment]
Help...

**Comment by Jitesh17** [comment]
It moved .. and this warning came and again stoped...
![termi1](https://user-images.githubusercontent.com/10935498/47985054-d8a72780-e11b-11e8-9e1b-83367ebe9a03.png)
`[ WARN] [1541404392.771543102]: TF to MSG: Quaternion Not Properly Normalized
`

**Comment by Jitesh17** [comment]
Please help.

Is the setup is not good ?
![2018-11-06-104950](https://user-images.githubusercontent.com/10935498/48037969-f7f09400-e1b1-11e8-818d-c06ce9275a39.jpg)

**Comment by Geo-fortune** [comment]
I also met the problem

**Comment by Jitesh17** [comment]
Have you found the solution?
Waiting...

**Comment by Geo-fortune** [comment]
> Have you found the solution?
> Waiting...

I rewrite the project based on opencv ros and pcl
