### ISSUE TITLE
lidar point goes wrong

### ISSUE THREAD

**Issue by dbsgws** [ankitdhall/lidar_camera_calibration#73]
Seems like lidar-point-clouds coordinates have a mapping.
Anyone have a same problem?
![2018-12-19 15-17-06](https://user-images.githubusercontent.com/32060126/50205068-ec43e000-03a1-11e9-9a37-5af9d9022de2.png)

**Comment by wangchuanhao1231** [comment]
I have the same problem, how did you solve it
