### ISSUE TITLE
Aruco_mapping appears to recognize only one aruco marker. When two are recognized, the Mono8 interface turns gray.

### ISSUE THREAD

**Issue by hunkyu** [ankitdhall/lidar_camera_calibration#82]
Aruco_mapping appears to recognize only one aruco marker. When two are recognized, the Mono8 interface turns gray.
![webwxgetmsgimg](https://user-images.githubusercontent.com/20533364/52690299-2bed0980-2f98-11e9-8adc-fd7406799ba1.jpeg)
![webwxgetmsgimg 2](https://user-images.githubusercontent.com/20533364/52690305-327b8100-2f98-11e9-8efa-b73e8f52ea25.jpeg)
![webwxgetmsgimg 1](https://user-images.githubusercontent.com/20533364/52690324-3c9d7f80-2f98-11e9-93b1-15e1eb45b1b2.jpeg)

**Comment by hunkyu** [comment]
I feel that the setup is fine, but at the same time there are two arcco makers that will crash.

**Comment by BmlmnnsDev** [comment]
Try to use the `--clock` argument when playing the rosbag. And use `<param name="/use_sim_time" value="true"/>`. I had the same issue. That configuration seemed to resolve that.

**Comment by hunkyu** [comment]
@BmlmnnsDev  But without rosbag play, I am using the topic of the camera obtained online.

**Comment by hunkyu** [comment]
@BmlmnnsDev  What do you mean by letting my rosbag record lidar and camera topic and then use --lock?

**Comment by hunkyu** [comment]
thank you ! @BmlmnnsDev
