### ISSUE TITLE
Why is the cloud interface point abnormal?

### ISSUE THREAD

**Issue by hunkyu** [ankitdhall/lidar_camera_calibration#83]
![screenshot from 2019-02-17 00-41-12](https://user-images.githubusercontent.com/20533364/52902569-a3978e80-324d-11e9-8557-34843cca7af8.png)
my config file:
[config_file.txt](https://github.com/ankitdhall/lidar_camera_calibration/files/2872167/config_file.txt)
1792 930
-2.5 2.5 
-4.0 4.0 
0 2.5
0.005
2
0
923.49779 0.0 861.95580 0.0
0.0 921.20685 435.44906 0.0
0.0 0.0 1.0 0.0
100
1.57 -1.57 0

**Comment by hunkyu** [comment]
![screenshot from 2019-02-17 11-50-54](https://user-images.githubusercontent.com/20533364/52908133-657c8800-32aa-11e9-8d20-01a70bd2794d.png)
![screenshot from 2019-02-17 11-51-08](https://user-images.githubusercontent.com/20533364/52908134-69100f00-32aa-11e9-98de-8ccfd6092ff2.png)
I changed the config configuration again, but there are still a lot of invalid points.
my config file:
1792 930
-3 3
-1.0 4.0
0 2.5
0.005
2
0
923.49779 0.0 861.95580 0.0
0.0 921.20685 435.44906 0.0
0.0 0.0 1.0 0.0
100
1.57 1.57 0

**Comment by ykk136** [comment]
Hello! Would you mind showing me your "find_transform.launch" file? Thank you..
