### ISSUE TITLE
where is the marker_6dof.h file?

### ISSUE THREAD

**Issue by UVCSzb** [ankitdhall/lidar_camera_calibration#85]
where is the marker_6dof.h file?

**Comment by XHwind** [comment]
I have the same problems and I have checked previous issues. But following the 3 processes in the install guide, I still have this problem when using catkin_make -DCATKIN_WHITELIST_PACKAGES="aruco_mapping;lidar_camera_calibration". If you have figured out how to solve this problem. Can you share it with us? Thanks a lot!!
